### PR TITLE
# 187300230 Integrate CirlceCI with readme badge

### PR DESCRIPTION
**Pull request by k3lly003**
### What does this PR do?
This PR addresses the requirements outlined in Pivotal ID #187300230. 
- Run codeclimate & test coverage after test run with CI.
- Integrate CirlceCI with readme badge 

### Description of Task to be completed?
I was given the task of adding a coverage badge in README file and connect code climate and config it with this repository  

### How should this be manually tested?
After pushing to GitHub navigate down in the repository's README section, from there you can view the coverage badge

### What are the relevant pivotal tracker/Trello stories?
Pivotal ID #187300230.

### CODE REVIEW

**Comment by PrinceRWIGIMBA** [comment]
@PrinceRWIGIMBA  Approved this pull request , also you forget to add the footer , check on that too

**Review by PrinceRWIGIMBA — APPROVED** [review]

**Review by emmanueltct — CHANGES_REQUESTED** [review]
squash your commit

**Review by emmanueltct — CHANGES_REQUESTED** [review]
squash your commit

**Review by sabatohura — CHANGES_REQUESTED** [review]
- You need to squash all your commits into one and also keep your commit message in present. like you have named your PR.

- Coverage and test reports are still unknown; we will test them out after merging with @kayigmb's PR.

**Pull request merged**
